on:
  push:
    branches:
      - develop
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      - name: Install
        run: npm install
      - name: Test
        run: npm test